######################################################################
##
## Filename: procesador_tb.udo
## Created on: Thu Oct 02 11:37:21 Hora de verano romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
