.TH "atoIp" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atoIp \- \fBatoIp\fP 
Convierte una cadena en formato Ip\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBchar\fP * \fBatoIp\fP \fB\fP(\fBchar\fP * str\fB\fP)
.SH "DESCRIPCIÓN"
.PP
Convierte una cadena con el valor decimal de la direccion IP En otra con el valor estandar 0\&.0\&.0\&.0
.PP
Recibe un array de char con el valor decimal de la IP
.SH "RETORNO"
.PP
Devuelve el valor de la ip en formato estandar 0\&.0\&.0\&.0
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
