.TH "commandCase" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commandCase \- \fBcommandCase\fP 
Recibe los mensajes del sevidor\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBint\fP \fBcurrent_page\fP \fB\fP(\fBvoid\fB\fP)\fP 
.SH "DESCRIPCIÓN"
.PP
Recibe con un bucle los mensajes del servidor, y los parsea y dependiendo del mensaje que reciba realiza opearaciones con lainterfaz\&.
.PP
No recibe nada\&.
.SH "RETORNO"
.PP
No devulve nada\&.
.SH "VER TAMBIÉN"
.PP
\fBnew_text(3)\fP, \fBdelete_page(3)\fP, \fBget_name_page(3)\fP, \fBset_current_page(3)\fP 
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
