.TH "moderated" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moderated \- \fBmoderated\fP 
Llamada por el checkbox de 'Moderado'\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBmoderated\fP \fB\fP(\fBgboolean\fB\fP)\fP 
.SH "DESCRIPCIÓN"
.PP
Es la función llamada cada vez que se selecciona o deselecciona el checkbox de 'Moderado'\&.
.PP
Recibe como parámetro de entrada el valor TRUE o FALSE según se active o desactive el botón de 'Moderado'\&.
.SH "RETORNO"
.PP
No devuelve ningún valor ni código de error\&.
.SH "VER TAMBIÉN"
.PP
\fBextern_msg(3)\fP, \fBtopic_protect(3)\fP, \fBsecret(3)\fP, \fBguests(3)\fP, \fBprivated(3)\fP\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es)
.PP
Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
