.TH "disconnect_client" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
disconnect_client \- \fBdisconnect_client\fP 
Llamada por el botón de 'Desconexión'\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBdisconnect_client\fP \fB\fP(\fBvoid\fB\fP)\fP 
.SH "DESCRIPCIÓN"
.PP
Es la función llamada cada vez que se pulsa el botón de 'Desconexión' en el interfaz gráfico\&.
.PP
No tiene parámetros de entrada\&.
.SH "RETORNO"
.PP
No devuelve ningún valor ni código de error\&.
.SH "VER TAMBIÉN"
.PP
\fBconnect_client(3)\fP\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
