.TH "clienteArchivo" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clienteArchivo \- \fBclienteArchivo\fP 
Prepara la conexion con el emisor del archivo
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBvoid\fP \fBclienteArchivo\fP \fB\fP(\fBvoid\fP * in \fB\fP)
.SH "DESCRIPCIÓN"
.PP
.PP
.nf
Funcion que establece un cliente para solicitar un archivo 
cuyo nombre se recibira mediante funciones globales.
.fi
.PP
.SH "RETORNO"
.PP
No devulve nada\&.
.SH "VER TAMBIÉN"
.PP
\fBservidorArchivo(3)\fP\&. 
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
