.TH "getTamanoFichero" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getTamanoFichero \- \fBclienteArchivo\fP 
Devuelve el tamaño de un fichero
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBint\fP \fBgetTamanoFichero\fP \fB\fP(\fBchar\fP * fichero \fB\fP)
.SH "DESCRIPCIÓN"
.PP
Dado el nombre de un fichero devulve su tamaño si este existe\&.
.PP
fichero sera el nombre del fichero a mandar\&.
.SH "RETORNO"
.PP
Devuelve el tamaño del fichero en caso de exito y -1 en caso de error\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
