.TH "guests" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guests \- \fBguests\fP 
Llamada por el checkbox de 'Invitados'\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBguests\fP \fB\fP(\fBgboolean\fB\fP)\fP 
.SH "DESCRIPCIÓN"
.PP
Es la función llamada cada vez que se selecciona o deselecciona el checkbox de 'Invitados'\&.
.PP
Recibe como parámetro de entrada el valor TRUE o FALSE según se active o desactive el botón de 'Invitados'\&.
.SH "RETORNO"
.PP
No devuelve ningún valor ni código de error\&.
.SH "VER TAMBIÉN"
.PP
\fBextern_msg(3)\fP, \fBtopic_protect(3)\fP, \fBsecret(3)\fP, \fBprivated(3)\fP, \fBmoderated(3)\fP\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
