.TH "recibir" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recibir \- \fBrecibir\fP 
pone un socket en modo de recepcion
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBint\fP \fBrecibir\fP \fB\fP(\fBint\fP sockfd ,\fBchar\fP * buf \fB\fP)
.SH "DESCRIPCIÓN"
.PP
Pone un socket en modo de recepcion, escribe el mensaje en buf y gestiona los errores\&.
.SH "RETORNO"
.PP
Devuelve -1 en caso de error y 0 en caso de exito\&.
.SH "VER TAMBIÉN"
.PP
\fBabrirSocketTCP(3)\fP, \fBabrirSocketUDP(3)\fP, \fBabrirBind(3)\fP, \fBabrirListen(3)\fP, \fBabrirConnect(3)\fP, \fBaceptar(3)\fP, \fBescribir(3)\fP\&. 
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
