.TH "servidorArchivo" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
servidorArchivo \- \fBservidorArchivo\fP 
Prepara la conexion con el emisor del archivo
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBvoid\fP \fBservidorArchivo\fP \fB\fP(\fBvoid\fP * in \fB\fP)
.SH "DESCRIPCIÓN"
.PP
Funcion que establece la conexion del lado del servidor para compartir un archivo que se ontendra mediante funciones globales ya que esta ideada para que use hilos\&.
.SH "RETORNO"
.PP
No devulve nada\&.
.SH "VER TAMBIÉN"
.PP
\fBclienteArchivo(3)\fP\&. 
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
