.TH "abrir_socket_t_c_p" 3 "Mon Apr 27 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
abrir_socket_t_c_p \- \fBabrirSocketTCP\fP 
Abre un socket UDP\&.
.PP
Abre un socket TCP
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBint\fP \fBabrirSocketTCP\fP \fB\fP( )
.SH "DESCRIPCIÓN"
.PP
Abre un socket TCP
.PP
Si ocurre un erro imprime un mensaje\&.
.SH "RETORNO"
.PP
Devuelve -1 en caso de error y 0 en caso de exito\&.
.SH "VER TAMBIÉN"
.PP
\fBabrirSocketUDP(3)\fP, \fBabrirBind(3)\fP, \fBabrirListen(3)\fP, \fBabrirConnect(3)\fP, \fBaceptar(3)\fP,\fBrecibir(3)\fP, \fBescribir(3)\fP\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es)
.PP
Abre un socket UDP
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBint\fP \fBabrirSocketUDP\fP \fB\fP( )
.SH "DESCRIPCIÓN"
.PP
Abre un socket UDP
.PP
Si ocurre un erro imprime un mensaje\&.
.SH "RETORNO"
.PP
Devuelve -1 en caso de error y 0 en caso de exito\&.
.SH "VER TAMBIÉN"
.PP
\fBabrirSocketTCP(3)\fP, \fBabrirBind(3)\fP, \fBabrirListen(3)\fP, \fBabrirConnect(3)\fP, \fBaceptar(3)\fP,\fBrecibir(3)\fP, \fBescribir(3)\fP\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
