######################################################################
##
## Filename: registros.udo
## Created on: Wed Oct 22 16:23:41 Hora de verano romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
