.TH "Ping" 3 "Thu Feb 26 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ping \- \fBPing\fP 
Hilo que se ejecuta continuamente mandando PING\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB<redes2/chat\&.h>\fP 
.PP
\fBvoid\fP \fBdisconnect_client\fP \fB\fP(\fBvoid\fB\fP)\fP 
.SH "DESCRIPCIÓN"
.PP
Envia PING al servidor cada 30 segundos mientras la conexion este activa\&.
.PP
No tiene parámetros de entrada\&.
.SH "RETORNO"
.PP
No devuelve ningún valor ni código de error\&.
.SH "VER TAMBIÉN"
.PP
\fB\fP 
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
