######################################################################
##
## Filename: MicroMIPSTb.udo
## Created on: Sun Apr 14 20:47:37 Hora de verano romance 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
