######################################################################
##
## Filename: microMIPS.udo
## Created on: Mon Apr 15 8:09:40 Hora de verano romance 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
