.TH "conectar_canal_seguro__s_s_l" 3 "Mon Apr 27 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conectar_canal_seguro__s_s_l \- \fBconectar_canal_seguro_SSL\fP 
realiza la conexion a un servidor SSL en esquema TCP\&.
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBSSL*\fP \fBconectar_canal_seguro_SSL\fP \fB\fP(\fBSSL_CTX*\fP ctx, \fBint\fP sockfd, \fBstruct\fP sockaddr res \fB\fP)
.SH "DESCRIPCIÓN"
.PP
Dado un contexto SSL y un descriptor de socket esta función se encargará de obtener un canal seguro SSL inciando el proceso de handshake con el otro extremo\&.
.SH "RETORNO"
.PP
Devuelve NULL en caso de error o la estructura SSL* inicializada en caso de exito\&.
.SH "VER TAMBIÉN"
.PP
\fBinicializar_nivel_SSL(3)\fP, \fBfijar_contexto_SSL(3)\fP, \fBaceptar_canal_seguro_SSL(3)\fP, \fBevaluar_post_connectar_SSL(3)\fP, \fBenviar_datos_SSL(3)\fP, \fBrecibir_datos_SSL(3)\fP, \fBcerrar_canal_SSL(3)\fP \fB\fP  authors AUTOR Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
