.TH "obtener_i_p_interface" 3 "Mon Apr 27 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obtener_i_p_interface \- \fBobtenerIPInterface\fP 
Obtiene la ip de una interfaz
.SH "SYNOPSIS"
.PP
\fB#include\fP \fB'conexion\&.h'\fP 
.PP
\fBuint8_t\fP \fBobtenerIPInterface\fP \fB\fP(\fBchar\fP * str char * interface \fB\fP, uint8_t* retorno \fB\fP)
.SH "DESCRIPCIÓN"
.PP
Devuelve la IP de un interfaz\&.
.PP
Recibe el nombre de la interfaz\&.
.PP
Recibe un enetero donde se rellena la direccion\&.
.SH "RETORNO"
.PP
Devuelve 0 en caso de error y 1 en caso de exito\&.
.SH "AUTOR"
.PP
Mario Valdemaro Garcia Roque (mariov.garcia@estudiante.uam.es) Roberto Garcia Teodoro (roberto.garciat@estudiante.uam.es) 
